services:
  frontend:
    build: ./frontend
    ports:
      - "3000:80"
    depends_on:
      - gateway

  gateway:
    build: ./gateway
    ports:
      - "8080:8080"
    environment:
      JWT_SECRET: supersecret
    depends_on:
      - auth
      - users

  auth:
    build: ./services/auth-service
    environment:
      JWT_SECRET: supersecret
      DB_HOST: db
      DB_USER: postgres
      DB_PASSWORD: postgres
      DB_NAME: app
    depends_on:
      - db

  users:
    build: ./services/user-service
    environment:
      DB_HOST: db
      DB_USER: postgres
      DB_PASSWORD: postgres
      DB_NAME: app
    depends_on:
      - db

  orders:
    build: ./services/order-service
    environment:
      DB_HOST: db
      DB_USER: postgres
      DB_PASSWORD: postgres
      DB_NAME: app
    depends_on:
      - db

  db:
    image: postgres:16-alpine
    environment:
      POSTGRES_DB: app
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./db:/docker-entrypoint-initdb.d
    ports:
      - "5433:5432"

  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    depends_on:
      - db

volumes:
  pgdata:
  pgadmin_data:
